services:
  server:
    build: ./express-container
    container_name: express-container
    ports:
      - "3000:3000"
    env_file:
      - ./express-container/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydocker
    networks:
      - fullstack-net
    depends_on:
      - mongo
    restart: unless-stopped
  client: 
    build: 
      context: ./react-container
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}   # Use at build time -> docker-compose up --build, picks variables from .env file
    container_name: react-container
    ports:
      - "5173:5173"
    networks:
      - fullstack-net
    depends_on:
      - server
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo-container 
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db   # data persists even if container restarts
    networks:
      - fullstack-net
    restart: unless-stopped

networks:
  fullstack-net:
    driver: bridge

volumes:
  mongo_data: